---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ is_default }} #true/false
provisioner: csi.trident.netapp.io
parameters:
  backendType: {{ backendType }}
  snapshots: {{ snapshots }}
  provisioningType: {{ provisioningType }}
  encryption: {{ encryption }}

