---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ name }}
provisioner: csi.trident.netapp.io
parameters:
  backendType: {{ backendType }}
  snapshots: {{ snapshots }}
  provisioningType: {{ provisioningType }}
  encryption: {{ encryption }}

